[versions]
bnd = "6.1.0"

[libraries]
bnd = { module = "biz.aQute.bnd:biz.aQute.bnd.gradle", version.ref = "bnd" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version = "0.20.0" }
metadata = { id = "com.github.sgtsilvio.gradle.metadata", version = "0.3.0" }
